repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4
    hooks:
      # Linter: fixes lint errors & sorts imports
      - id: ruff
        args: [--fix]
      - id: ruff-format